import { Metadata } from "next";
import { Inter, Nunito, Roboto, Poppins } from "next/font/google";

export const inter = Inter({ subsets: ["latin"] });
export const nunito = Nunito({ subsets: ["latin"] });
export const roboto = Roboto({ subsets: ["latin"], weight: "500" });
export const poppins = Poppins({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "Dev Phantom Test",
  description: "Generated by create next app",
};
